{ fetchgit, goPackages, runCommand, stdenv, ... }:
let
  # Godeps.nix generated by:
  #   git clone https://github.com/hashicorp/vault /tmp/go/src/github.com/hashicorp/vault
  #   export XC_ARCH=amd64 XC_OS=linux PATH=/tmp/go/bin:$PATH GOPATH=/tmp/go
  #   make -C /tmp/go/src/github.com/hashicorp/vault bootstrap
  #   make -C /tmp/go/src/github.com/hashicorp/vault bin
  #   ./Godeps2nix.sh /tmp/go/src/github.com/hashicorp/vault/Godeps/Godeps.json > Godeps.nix
  # using https://gist.github.com/4z3/54b74d5324af82f52dc2#file-godeps2nix-sh
  Godeps = import ./Godeps.nix { inherit runCommand fetchgit; };
in

stdenv.mkDerivation rec {
  name = "vault-0.4.0";
  src = fetchgit {
    url = https://github.com/hashicorp/vault;
    rev = "refs/tags/v0.4.0";
    sha256 = "143q2ng6rcci34d9mz36b4dpq75hd81f242ar94d2zxzmp5jy5mj";
  };

  buildPhase = ''
    mkdir deps self
    ln -s ${Godeps} deps/src
    mkdir -p self/src/github.com/hashicorp
    ln -s $PWD self/src/github.com/hashicorp/vault
    export GOPATH=$PWD/deps:$PWD/self
    mkdir workdir
    cd workdir
    ${goPackages.go}/bin/go build -v github.com/hashicorp/vault
  '';

  installPhase = ''
    mkdir -p $out/bin
    cp vault $out/bin
  '';
}
