#
# This file **used to** be auto-generated by cabal2nix. Edit with care.
#

{ cabal, aeson, attoparsec, caseInsensitive, certificate
, cryptoRandom, dataDefault, hslogger, httpConduit, httpKit
, httpTypes, interpolatedstringPerl6, mtl, network
, optparseApplicative, safe, SHA
, split, stringConversions, time, tls, unorderedContainers
, utf8String, x509, yaml
, fetchgit, makeWrapper
}:

cabal.mkDerivation (self: {
  pname = "sproxy";
  version = "0.8.0";

  src = fetchgit {
    url = "git://github.com/zalora/sproxy.git";
    rev = "c3e999cf381483f6ff64612ff1c2eaff5ea375f2";
    sha256 = "fbf706eb34225f99f04eadc87fd04128292f77b0de1b59ab3c976d67e7dd0b3b";
  };

  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson attoparsec caseInsensitive certificate cryptoRandom
    dataDefault hslogger httpConduit httpKit httpTypes
    interpolatedstringPerl6 mtl network optparseApplicative
    safe SHA split stringConversions time
    tls unorderedContainers utf8String x509 yaml
  ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };

  postInstall = ''
    rm -rf $out/lib $out/share/doc
    source ${makeWrapper}/nix-support/setup-hook
    wrapProgram $out/bin/sproxy --prefix LD_LIBRARY_PATH : ${self.stdenv.gcc.gcc}/lib64
  '';
})
