# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, derive, fetchzip, hspec, hspecExpectations
, mtl, mtlCompat, QuickCheck, text, time, transformersCompat
}:

cabal.mkDerivation (self: {
  pname = "cron";
  version = "0.3.0";
  src = fetchzip {
    url = "https://github.com/proger/cron/archive/unicron.zip";
    sha256 = "02lr2ykxhfbzrq10z5cd5cf9019pls22f3wk6xdvg68p1gy43hmm";
  };
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ attoparsec mtl mtlCompat text time ];
  testDepends = [
    attoparsec derive hspec hspecExpectations QuickCheck text time
    transformersCompat
  ];
  doCheck = false;
  meta = {
    homepage = "http://github.com/michaelxavier/cron";
    description = "Cron datatypes and Attoparsec parser";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
