# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, fetchzip, transformers }:

cabal.mkDerivation (self: {
  pname = "transformers-compat";
  version = "0.4.0.4";
  src = fetchzip {
    url = "http://hackage.haskell.org/package/transformers-compat-0.4.0.4/transformers-compat-0.4.0.4.tar.gz";
    sha256 = "11m4cyk2b12bbiiy23i5n15bs2xw7pz93jm8rr44mbj6m2f4qm10";
  };
  buildDepends = [ transformers ];
  meta = {
    homepage = "http://github.com/ekmett/transformers-compat/";
    description = "A small compatibility shim exposing the new types from transformers 0.3 and 0.4 to older Haskell platforms.";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
