[
  <nixpkgs/nixos/modules/config/fonts/corefonts.nix>
  <nixpkgs/nixos/modules/config/i18n.nix>
  <nixpkgs/nixos/modules/config/networking.nix>
  <nixpkgs/nixos/modules/config/no-x-libs.nix>
  <nixpkgs/nixos/modules/config/nsswitch.nix>
  <nixpkgs/nixos/modules/config/shells-environment.nix>
  <nixpkgs/nixos/modules/config/swap.nix>
  <nixpkgs/nixos/modules/config/sysctl.nix>
  <nixpkgs/nixos/modules/config/system-environment.nix>
  <nixpkgs/nixos/modules/config/system-path.nix>
  <nixpkgs/nixos/modules/config/timezone.nix>
  <nixpkgs/nixos/modules/config/users-groups.nix>
  <nixpkgs/nixos/modules/installer/tools/tools.nix>
  <nixpkgs/nixos/modules/misc/assertions.nix>
  <nixpkgs/nixos/modules/misc/extra-arguments.nix>
  <nixpkgs/nixos/modules/misc/ids.nix>
  <nixpkgs/nixos/modules/misc/lib.nix>
  <nixpkgs/nixos/modules/misc/nixpkgs.nix>
  <nixpkgs/nixos/modules/misc/version.nix>
  <nixpkgs/nixos/modules/programs/bash/bash.nix>
  <nixpkgs/nixos/modules/programs/environment.nix>
  <nixpkgs/nixos/modules/programs/shadow.nix>
  <nixpkgs/nixos/modules/programs/shell.nix>
  <nixpkgs/nixos/modules/programs/ssh.nix>
  <nixpkgs/nixos/modules/security/ca.nix>
  <nixpkgs/nixos/modules/security/pam.nix>
  <nixpkgs/nixos/modules/security/setuid-wrappers.nix>
  <nixpkgs/nixos/modules/security/sudo.nix>
  <nixpkgs/nixos/modules/services/audio/alsa.nix>
  <nixpkgs/nixos/modules/services/hardware/actkbd.nix>
  <nixpkgs/nixos/modules/services/hardware/udev.nix>
  <nixpkgs/nixos/modules/services/misc/nix-daemon.nix>
  <nixpkgs/nixos/modules/services/misc/nix-gc.nix>
  <nixpkgs/nixos/modules/services/misc/nix-ssh-serve.nix>
  <nixpkgs/nixos/modules/services/networking/dhcpcd.nix>
  <nixpkgs/nixos/modules/services/networking/firewall.nix>
  <nixpkgs/nixos/modules/services/networking/ssh/sshd.nix>
  <nixpkgs/nixos/modules/services/scheduling/cron.nix>
  <nixpkgs/nixos/modules/services/system/dbus.nix>
  <nixpkgs/nixos/modules/services/system/nscd.nix>
  <nixpkgs/nixos/modules/services/ttys/agetty.nix>
  <nixpkgs/nixos/modules/system/activation/activation-script.nix>
  <nixpkgs/nixos/modules/system/activation/top-level.nix>
  <nixpkgs/nixos/modules/system/boot/emergency-mode.nix>
  <nixpkgs/nixos/modules/system/boot/initrd-network.nix>
  <nixpkgs/nixos/modules/system/boot/kernel.nix>
  <nixpkgs/nixos/modules/system/boot/loader/efi.nix>
  <nixpkgs/nixos/modules/system/boot/loader/grub/grub.nix>
  <nixpkgs/nixos/modules/system/boot/loader/loader.nix>
  <nixpkgs/nixos/modules/system/boot/modprobe.nix>
  <nixpkgs/nixos/modules/system/boot/shutdown.nix>
  <nixpkgs/nixos/modules/system/boot/stage-1.nix>
  <nixpkgs/nixos/modules/system/boot/stage-2.nix>
  <nixpkgs/nixos/modules/system/boot/systemd.nix>
  <nixpkgs/nixos/modules/system/boot/tmp.nix>
  <nixpkgs/nixos/modules/system/etc/etc.nix>
  <nixpkgs/nixos/modules/tasks/filesystems.nix>
  <nixpkgs/nixos/modules/tasks/filesystems/ext.nix>
  <nixpkgs/nixos/modules/tasks/network-interfaces.nix>
  <nixpkgs/nixos/modules/virtualisation/amazon-options.nix>
]
