[
  <nixpkgs/nixos/modules/config/fonts/corefonts.nix>
  <nixpkgs/nixos/modules/config/i18n.nix>
  <nixpkgs/nixos/modules/config/networking.nix>
  <nixpkgs/nixos/modules/config/no-x-libs.nix>
  <nixpkgs/nixos/modules/config/nsswitch.nix>
  <nixpkgs/nixos/modules/config/power-management.nix>
  <nixpkgs/nixos/modules/config/shells-environment.nix>
  <nixpkgs/nixos/modules/config/swap.nix>
  <nixpkgs/nixos/modules/config/sysctl.nix>
  <nixpkgs/nixos/modules/config/system-environment.nix>
  <nixpkgs/nixos/modules/config/system-path.nix>
  <nixpkgs/nixos/modules/config/timezone.nix>
  <nixpkgs/nixos/modules/config/users-groups.nix>
  <nixpkgs/nixos/modules/hardware/all-firmware.nix>
  <nixpkgs/nixos/modules/misc/assertions.nix>
  <nixpkgs/nixos/modules/misc/check-config.nix>
  <nixpkgs/nixos/modules/misc/ids.nix>
  <nixpkgs/nixos/modules/misc/lib.nix>
  <nixpkgs/nixos/modules/misc/nixpkgs.nix>
  <nixpkgs/nixos/modules/misc/version.nix>
  <nixpkgs/nixos/modules/programs/bash/bash.nix>
  <nixpkgs/nixos/modules/programs/environment.nix>
  <nixpkgs/nixos/modules/programs/shadow.nix>
  <nixpkgs/nixos/modules/programs/shell.nix>
  <nixpkgs/nixos/modules/programs/ssh.nix>
  <nixpkgs/nixos/modules/security/pam.nix>
  <nixpkgs/nixos/modules/security/pam_usb.nix>
  <nixpkgs/nixos/modules/security/polkit.nix>
  <nixpkgs/nixos/modules/security/setuid-wrappers.nix>
  <nixpkgs/nixos/modules/security/sudo.nix>
  <nixpkgs/nixos/modules/services/hardware/udev.nix>
  <nixpkgs/nixos/modules/services/hardware/udisks2.nix>
  <nixpkgs/nixos/modules/services/logging/logrotate.nix>
  <nixpkgs/nixos/modules/services/logging/syslog-ng.nix>
  <nixpkgs/nixos/modules/services/misc/nix-daemon.nix>
  <nixpkgs/nixos/modules/services/misc/nix-gc.nix>
  <nixpkgs/nixos/modules/services/misc/nix-ssh-serve.nix>
  <nixpkgs/nixos/modules/services/misc/nixos-manual.nix>
  <nixpkgs/nixos/modules/services/networking/dhcpcd.nix>
  <nixpkgs/nixos/modules/services/networking/firewall.nix>
  <nixpkgs/nixos/modules/services/networking/ntpd.nix>
  <nixpkgs/nixos/modules/services/networking/ssh/sshd.nix>
  <nixpkgs/nixos/modules/services/scheduling/cron.nix>
  <nixpkgs/nixos/modules/services/system/dbus.nix>
  <nixpkgs/nixos/modules/services/system/nscd.nix>
  <nixpkgs/nixos/modules/services/ttys/agetty.nix>
  <nixpkgs/nixos/modules/system/activation/activation-script.nix>
  <nixpkgs/nixos/modules/system/activation/top-level.nix>
  <nixpkgs/nixos/modules/system/boot/kernel.nix>
  <nixpkgs/nixos/modules/system/boot/loader/grub/grub.nix>
  <nixpkgs/nixos/modules/system/boot/modprobe.nix>
  <nixpkgs/nixos/modules/system/boot/shutdown.nix>
  <nixpkgs/nixos/modules/system/boot/stage-1.nix>
  <nixpkgs/nixos/modules/system/boot/stage-2.nix>
  <nixpkgs/nixos/modules/system/boot/systemd.nix>
  <nixpkgs/nixos/modules/system/boot/tmp.nix>
  <nixpkgs/nixos/modules/system/etc/etc.nix>
  <nixpkgs/nixos/modules/system/upstart/upstart.nix>
  <nixpkgs/nixos/modules/tasks/cpu-freq.nix>
  <nixpkgs/nixos/modules/tasks/filesystems.nix>
  <nixpkgs/nixos/modules/tasks/filesystems/ext.nix>
  <nixpkgs/nixos/modules/tasks/kbd.nix>
  <nixpkgs/nixos/modules/tasks/network-interfaces.nix>
  <nixpkgs/nixos/modules/tasks/scsi-link-power-management.nix>
  <nixpkgs/nixos/modules/virtualisation/containers.nix>
  <nixpkgs/nixos/modules/virtualisation/docker.nix>
  <nixpkgs/nixos/modules/virtualisation/virtualbox-guest.nix>

  ## <nixpkgs/nixos/modules/services/audio/fuppes.nix>
  ## Disabled as fuppes it does no longer builds.>
  ##<nixpkgs/nixos/modules/services/misc/autofs.nix>
  ##<nixpkgs/nixos/modules/services/x11/window-managers/compiz.nix>
  #<nixpkgs/nixos/modules/config/gnu.nix>
  #<nixpkgs/nixos/modules/config/gtk-exe-env.nix>
  #<nixpkgs/nixos/modules/config/krb5.nix>
  #<nixpkgs/nixos/modules/config/ldap.nix>
  #<nixpkgs/nixos/modules/config/pulseaudio.nix>
  #<nixpkgs/nixos/modules/config/qt-plugin-env.nix>
  #<nixpkgs/nixos/modules/config/unix-odbc-drivers.nix>
  #<nixpkgs/nixos/modules/config/vpnc.nix>
  #<nixpkgs/nixos/modules/config/zram.nix>
  #<nixpkgs/nixos/modules/hardware/cpu/amd-microcode.nix>
  #<nixpkgs/nixos/modules/hardware/cpu/intel-microcode.nix>
  #<nixpkgs/nixos/modules/hardware/network/b43.nix>
  #<nixpkgs/nixos/modules/hardware/network/intel-2100bg.nix>
  #<nixpkgs/nixos/modules/hardware/network/intel-2200bg.nix>
  #<nixpkgs/nixos/modules/hardware/network/intel-3945abg.nix>
  #<nixpkgs/nixos/modules/hardware/network/ralink.nix>
  #<nixpkgs/nixos/modules/hardware/network/rtl8192c.nix>
  #<nixpkgs/nixos/modules/hardware/opengl.nix>
  #<nixpkgs/nixos/modules/hardware/pcmcia.nix>
  #<nixpkgs/nixos/modules/hardware/video/ati.nix>
  #<nixpkgs/nixos/modules/hardware/video/bumblebee.nix>
  #<nixpkgs/nixos/modules/hardware/video/nvidia.nix>
  #<nixpkgs/nixos/modules/installer/tools/nixos-checkout.nix>
  #<nixpkgs/nixos/modules/installer/tools/tools.nix>
  #<nixpkgs/nixos/modules/misc/crashdump.nix>
  #<nixpkgs/nixos/modules/misc/locate.nix>
  #<nixpkgs/nixos/modules/misc/meta.nix>
  #<nixpkgs/nixos/modules/misc/passthru.nix>
  #<nixpkgs/nixos/modules/programs/atop.nix>
  #<nixpkgs/nixos/modules/programs/bash/command-not-found.nix>
  #<nixpkgs/nixos/modules/programs/blcr.nix>
  #<nixpkgs/nixos/modules/programs/dconf.nix>
  #<nixpkgs/nixos/modules/programs/freetds.nix>
  #<nixpkgs/nixos/modules/programs/info.nix>
  #<nixpkgs/nixos/modules/programs/light.nix>
  #<nixpkgs/nixos/modules/programs/nano.nix>
  #<nixpkgs/nixos/modules/programs/screen.nix>
  #<nixpkgs/nixos/modules/programs/ssmtp.nix>
  #<nixpkgs/nixos/modules/programs/uim.nix>
  #<nixpkgs/nixos/modules/programs/venus.nix>
  #<nixpkgs/nixos/modules/programs/virtualbox-host.nix>
  #<nixpkgs/nixos/modules/programs/wvdial.nix>
  #<nixpkgs/nixos/modules/programs/zsh/zsh.nix>
  #<nixpkgs/nixos/modules/rename.nix>
  #<nixpkgs/nixos/modules/security/apparmor-suid.nix>
  #<nixpkgs/nixos/modules/security/apparmor.nix>
  #<nixpkgs/nixos/modules/security/ca.nix>
  #<nixpkgs/nixos/modules/security/duosec.nix>
  #<nixpkgs/nixos/modules/security/grsecurity.nix>
  #<nixpkgs/nixos/modules/security/prey.nix>
  #<nixpkgs/nixos/modules/security/rngd.nix>
  #<nixpkgs/nixos/modules/security/rtkit.nix>
  #<nixpkgs/nixos/modules/services/amqp/activemq/default.nix>
  #<nixpkgs/nixos/modules/services/amqp/rabbitmq.nix>
  #<nixpkgs/nixos/modules/services/audio/alsa.nix>
  #<nixpkgs/nixos/modules/services/audio/liquidsoap.nix>
  #<nixpkgs/nixos/modules/services/audio/mopidy.nix>
  #<nixpkgs/nixos/modules/services/audio/mpd.nix>
  #<nixpkgs/nixos/modules/services/backup/almir.nix>
  #<nixpkgs/nixos/modules/services/backup/bacula.nix>
  #<nixpkgs/nixos/modules/services/backup/crashplan.nix>
  #<nixpkgs/nixos/modules/services/backup/mysql-backup.nix>
  #<nixpkgs/nixos/modules/services/backup/postgresql-backup.nix>
  #<nixpkgs/nixos/modules/services/backup/rsnapshot.nix>
  #<nixpkgs/nixos/modules/services/backup/sitecopy-backup.nix>
  #<nixpkgs/nixos/modules/services/backup/tarsnap.nix>
  #<nixpkgs/nixos/modules/services/cluster/fleet.nix>
  #<nixpkgs/nixos/modules/services/cluster/kubernetes.nix>
  #<nixpkgs/nixos/modules/services/computing/torque/mom.nix>
  #<nixpkgs/nixos/modules/services/computing/torque/server.nix>
  #<nixpkgs/nixos/modules/services/continuous-integration/jenkins/default.nix>
  #<nixpkgs/nixos/modules/services/continuous-integration/jenkins/slave.nix>
  #<nixpkgs/nixos/modules/services/databases/4store-endpoint.nix>
  #<nixpkgs/nixos/modules/services/databases/4store.nix>
  #<nixpkgs/nixos/modules/services/databases/couchdb.nix>
  #<nixpkgs/nixos/modules/services/databases/firebird.nix>
  #<nixpkgs/nixos/modules/services/databases/hbase.nix>
  #<nixpkgs/nixos/modules/services/databases/influxdb.nix>
  #<nixpkgs/nixos/modules/services/databases/memcached.nix>
  #<nixpkgs/nixos/modules/services/databases/monetdb.nix>
  #<nixpkgs/nixos/modules/services/databases/mongodb.nix>
  #<nixpkgs/nixos/modules/services/databases/mysql.nix>
  #<nixpkgs/nixos/modules/services/databases/neo4j.nix>
  #<nixpkgs/nixos/modules/services/databases/openldap.nix>
  #<nixpkgs/nixos/modules/services/databases/opentsdb.nix>
  #<nixpkgs/nixos/modules/services/databases/postgresql.nix>
  #<nixpkgs/nixos/modules/services/databases/redis.nix>
  #<nixpkgs/nixos/modules/services/databases/virtuoso.nix>
  #<nixpkgs/nixos/modules/services/desktops/accountsservice.nix>
  #<nixpkgs/nixos/modules/services/desktops/geoclue2.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/at-spi2-core.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/evolution-data-server.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/gnome-documents.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/gnome-keyring.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/gnome-online-accounts.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/gnome-online-miners.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/gnome-user-share.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/gvfs.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/seahorse.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/sushi.nix>
  #<nixpkgs/nixos/modules/services/desktops/gnome3/tracker.nix>
  #<nixpkgs/nixos/modules/services/desktops/telepathy.nix>
  #<nixpkgs/nixos/modules/services/games/ghost-one.nix>
  #<nixpkgs/nixos/modules/services/games/minecraft-server.nix>
  #<nixpkgs/nixos/modules/services/hardware/acpid.nix>
  #<nixpkgs/nixos/modules/services/hardware/amd-hybrid-graphics.nix>
  #<nixpkgs/nixos/modules/services/hardware/bluetooth.nix>
  #<nixpkgs/nixos/modules/services/hardware/nvidia-optimus.nix>
  #<nixpkgs/nixos/modules/services/hardware/pcscd.nix>
  #<nixpkgs/nixos/modules/services/hardware/pommed.nix>
  #<nixpkgs/nixos/modules/services/hardware/sane.nix>
  #<nixpkgs/nixos/modules/services/hardware/tcsd.nix>
  #<nixpkgs/nixos/modules/services/hardware/thinkfan.nix>
  #<nixpkgs/nixos/modules/services/hardware/upower.nix>
  #<nixpkgs/nixos/modules/services/logging/klogd.nix>
  #<nixpkgs/nixos/modules/services/logging/logcheck.nix>
  #<nixpkgs/nixos/modules/services/logging/logstash.nix>
  #<nixpkgs/nixos/modules/services/logging/rsyslogd.nix>
  #<nixpkgs/nixos/modules/services/logging/syslogd.nix>
  #<nixpkgs/nixos/modules/services/mail/dovecot.nix>
  #<nixpkgs/nixos/modules/services/mail/freepops.nix>
  #<nixpkgs/nixos/modules/services/mail/mail.nix>
  #<nixpkgs/nixos/modules/services/mail/mlmmj.nix>
  #<nixpkgs/nixos/modules/services/mail/opensmtpd.nix>
  #<nixpkgs/nixos/modules/services/mail/postfix.nix>
  #<nixpkgs/nixos/modules/services/mail/spamassassin.nix>
  #<nixpkgs/nixos/modules/services/misc/cgminer.nix>
  #<nixpkgs/nixos/modules/services/misc/cpuminer-cryptonight.nix>
  #<nixpkgs/nixos/modules/services/misc/dictd.nix>
  #<nixpkgs/nixos/modules/services/misc/disnix.nix>
  #<nixpkgs/nixos/modules/services/misc/docker-registry.nix>
  #<nixpkgs/nixos/modules/services/misc/etcd.nix>
  #<nixpkgs/nixos/modules/services/misc/felix.nix>
  #<nixpkgs/nixos/modules/services/misc/folding-at-home.nix>
  #<nixpkgs/nixos/modules/services/misc/gitlab.nix>
  #<nixpkgs/nixos/modules/services/misc/gitolite.nix>
  #<nixpkgs/nixos/modules/services/misc/gpsd.nix>
  #<nixpkgs/nixos/modules/services/misc/mesos-master.nix>
  #<nixpkgs/nixos/modules/services/misc/mesos-slave.nix>
  #<nixpkgs/nixos/modules/services/misc/phd.nix>
  #<nixpkgs/nixos/modules/services/misc/redmine.nix>
  #<nixpkgs/nixos/modules/services/misc/rippled.nix>
  #<nixpkgs/nixos/modules/services/misc/rogue.nix>
  #<nixpkgs/nixos/modules/services/misc/siproxd.nix>
  #<nixpkgs/nixos/modules/services/misc/svnserve.nix>
  #<nixpkgs/nixos/modules/services/misc/synergy.nix>
  #<nixpkgs/nixos/modules/services/misc/uhub.nix>
  #<nixpkgs/nixos/modules/services/misc/zookeeper.nix>
  #<nixpkgs/nixos/modules/services/monitoring/apcupsd.nix>
  #<nixpkgs/nixos/modules/services/monitoring/bosun.nix>
  #<nixpkgs/nixos/modules/services/monitoring/collectd.nix>
  #<nixpkgs/nixos/modules/services/monitoring/dd-agent.nix>
  #<nixpkgs/nixos/modules/services/monitoring/graphite.nix>
  #<nixpkgs/nixos/modules/services/monitoring/monit.nix>
  #<nixpkgs/nixos/modules/services/monitoring/munin.nix>
  #<nixpkgs/nixos/modules/services/monitoring/nagios.nix>
  #<nixpkgs/nixos/modules/services/monitoring/riemann-dash.nix>
  #<nixpkgs/nixos/modules/services/monitoring/riemann.nix>
  #<nixpkgs/nixos/modules/services/monitoring/scollector.nix>
  #<nixpkgs/nixos/modules/services/monitoring/smartd.nix>
  #<nixpkgs/nixos/modules/services/monitoring/statsd.nix>
  #<nixpkgs/nixos/modules/services/monitoring/systemhealth.nix>
  #<nixpkgs/nixos/modules/services/monitoring/ups.nix>
  #<nixpkgs/nixos/modules/services/monitoring/uptime.nix>
  #<nixpkgs/nixos/modules/services/monitoring/zabbix-agent.nix>
  #<nixpkgs/nixos/modules/services/monitoring/zabbix-server.nix>
  #<nixpkgs/nixos/modules/services/network-filesystems/diod.nix>
  #<nixpkgs/nixos/modules/services/network-filesystems/drbd.nix>
  #<nixpkgs/nixos/modules/services/network-filesystems/nfsd.nix>
  #<nixpkgs/nixos/modules/services/network-filesystems/openafs-client/default.nix>
  #<nixpkgs/nixos/modules/services/network-filesystems/rsyncd.nix>
  #<nixpkgs/nixos/modules/services/network-filesystems/samba.nix>
  #<nixpkgs/nixos/modules/services/network-filesystems/yandex-disk.nix>
  #<nixpkgs/nixos/modules/services/networking/amuled.nix>
  #<nixpkgs/nixos/modules/services/networking/atftpd.nix>
  #<nixpkgs/nixos/modules/services/networking/avahi-daemon.nix>
  #<nixpkgs/nixos/modules/services/networking/bind.nix>
  #<nixpkgs/nixos/modules/services/networking/bitlbee.nix>
  #<nixpkgs/nixos/modules/services/networking/btsync.nix>
  #<nixpkgs/nixos/modules/services/networking/chrony.nix>
  #<nixpkgs/nixos/modules/services/networking/cjdns.nix>
  #<nixpkgs/nixos/modules/services/networking/cntlm.nix>
  #<nixpkgs/nixos/modules/services/networking/connman.nix>
  #<nixpkgs/nixos/modules/services/networking/consul.nix>
  #<nixpkgs/nixos/modules/services/networking/ddclient.nix>
  #<nixpkgs/nixos/modules/services/networking/dhcpd.nix>
  #<nixpkgs/nixos/modules/services/networking/dnscrypt-proxy.nix>
  #<nixpkgs/nixos/modules/services/networking/dnsmasq.nix>
  #<nixpkgs/nixos/modules/services/networking/ejabberd.nix>
  #<nixpkgs/nixos/modules/services/networking/flashpolicyd.nix>
  #<nixpkgs/nixos/modules/services/networking/freenet.nix>
  #<nixpkgs/nixos/modules/services/networking/git-daemon.nix>
  #<nixpkgs/nixos/modules/services/networking/gnunet.nix>
  #<nixpkgs/nixos/modules/services/networking/gogoclient.nix>
  #<nixpkgs/nixos/modules/services/networking/gvpe.nix>
  #<nixpkgs/nixos/modules/services/networking/haproxy.nix>
  #<nixpkgs/nixos/modules/services/networking/hostapd.nix>
  #<nixpkgs/nixos/modules/services/networking/i2pd.nix>
  #<nixpkgs/nixos/modules/services/networking/ifplugd.nix>
  #<nixpkgs/nixos/modules/services/networking/iodined.nix>
  #<nixpkgs/nixos/modules/services/networking/ircd-hybrid/default.nix>
  #<nixpkgs/nixos/modules/services/networking/kippo.nix>
  #<nixpkgs/nixos/modules/services/networking/mailpile.nix>
  #<nixpkgs/nixos/modules/services/networking/minidlna.nix>
  #<nixpkgs/nixos/modules/services/networking/murmur.nix>
  #<nixpkgs/nixos/modules/services/networking/nat.nix>
  #<nixpkgs/nixos/modules/services/networking/networkmanager.nix>
  #<nixpkgs/nixos/modules/services/networking/ngircd.nix>
  #<nixpkgs/nixos/modules/services/networking/notbit.nix>
  #<nixpkgs/nixos/modules/services/networking/nsd.nix>
  #<nixpkgs/nixos/modules/services/networking/ntopng.nix>
  #<nixpkgs/nixos/modules/services/networking/oidentd.nix>
  #<nixpkgs/nixos/modules/services/networking/openfire.nix>
  #<nixpkgs/nixos/modules/services/networking/openntpd.nix>
  #<nixpkgs/nixos/modules/services/networking/openvpn.nix>
  #<nixpkgs/nixos/modules/services/networking/polipo.nix>
  #<nixpkgs/nixos/modules/services/networking/prayer.nix>
  #<nixpkgs/nixos/modules/services/networking/privoxy.nix>
  #<nixpkgs/nixos/modules/services/networking/prosody.nix>
  #<nixpkgs/nixos/modules/services/networking/quassel.nix>
  #<nixpkgs/nixos/modules/services/networking/radicale.nix>
  #<nixpkgs/nixos/modules/services/networking/radvd.nix>
  #<nixpkgs/nixos/modules/services/networking/rdnssd.nix>
  #<nixpkgs/nixos/modules/services/networking/rpcbind.nix>
  #<nixpkgs/nixos/modules/services/networking/sabnzbd.nix>
  #<nixpkgs/nixos/modules/services/networking/searx.nix>
  #<nixpkgs/nixos/modules/services/networking/seeks.nix>
  #<nixpkgs/nixos/modules/services/networking/spiped.nix>
  #<nixpkgs/nixos/modules/services/networking/ssh/lshd.nix>
  #<nixpkgs/nixos/modules/services/networking/strongswan.nix>
  #<nixpkgs/nixos/modules/services/networking/supybot.nix>
  #<nixpkgs/nixos/modules/services/networking/syncthing.nix>
  #<nixpkgs/nixos/modules/services/networking/tcpcrypt.nix>
  #<nixpkgs/nixos/modules/services/networking/teamspeak3.nix>
  #<nixpkgs/nixos/modules/services/networking/tftpd.nix>
  #<nixpkgs/nixos/modules/services/networking/unbound.nix>
  #<nixpkgs/nixos/modules/services/networking/unifi.nix>
  #<nixpkgs/nixos/modules/services/networking/vsftpd.nix>
  #<nixpkgs/nixos/modules/services/networking/wakeonlan.nix>
  #<nixpkgs/nixos/modules/services/networking/websockify.nix>
  #<nixpkgs/nixos/modules/services/networking/wicd.nix>
  #<nixpkgs/nixos/modules/services/networking/wpa_supplicant.nix>
  #<nixpkgs/nixos/modules/services/networking/xinetd.nix>
  #<nixpkgs/nixos/modules/services/networking/znc.nix>
  #<nixpkgs/nixos/modules/services/printing/cupsd.nix>
  #<nixpkgs/nixos/modules/services/scheduling/atd.nix>
  #<nixpkgs/nixos/modules/services/scheduling/chronos.nix>
  #<nixpkgs/nixos/modules/services/scheduling/fcron.nix>
  #<nixpkgs/nixos/modules/services/search/elasticsearch.nix>
  #<nixpkgs/nixos/modules/services/search/solr.nix>
  #<nixpkgs/nixos/modules/services/security/clamav.nix>
  #<nixpkgs/nixos/modules/services/security/fail2ban.nix>
  #<nixpkgs/nixos/modules/services/security/fprot.nix>
  #<nixpkgs/nixos/modules/services/security/frandom.nix>
  #<nixpkgs/nixos/modules/services/security/haveged.nix>
  #<nixpkgs/nixos/modules/services/security/tor.nix>
  #<nixpkgs/nixos/modules/services/security/torify.nix>
  #<nixpkgs/nixos/modules/services/security/torsocks.nix>
  #<nixpkgs/nixos/modules/services/system/kerberos.nix>
  #<nixpkgs/nixos/modules/services/system/uptimed.nix>
  #<nixpkgs/nixos/modules/services/torrent/deluge.nix>
  #<nixpkgs/nixos/modules/services/torrent/peerflix.nix>
  #<nixpkgs/nixos/modules/services/torrent/transmission.nix>
  #<nixpkgs/nixos/modules/services/ttys/gpm.nix>
  #<nixpkgs/nixos/modules/services/ttys/kmscon.nix>
  #<nixpkgs/nixos/modules/services/web-servers/apache-httpd/default.nix>
  #<nixpkgs/nixos/modules/services/web-servers/fcgiwrap.nix>
  #<nixpkgs/nixos/modules/services/web-servers/jboss/default.nix>
  #<nixpkgs/nixos/modules/services/web-servers/lighttpd/cgit.nix>
  #<nixpkgs/nixos/modules/services/web-servers/lighttpd/default.nix>
  #<nixpkgs/nixos/modules/services/web-servers/lighttpd/gitweb.nix>
  #<nixpkgs/nixos/modules/services/web-servers/nginx/default.nix>
  #<nixpkgs/nixos/modules/services/web-servers/phpfpm.nix>
  #<nixpkgs/nixos/modules/services/web-servers/tomcat.nix>
  #<nixpkgs/nixos/modules/services/web-servers/varnish/default.nix>
  #<nixpkgs/nixos/modules/services/web-servers/winstone.nix>
  #<nixpkgs/nixos/modules/services/web-servers/zope2.nix>
  #<nixpkgs/nixos/modules/services/x11/desktop-managers/default.nix>
  #<nixpkgs/nixos/modules/services/x11/display-managers/auto.nix>
  #<nixpkgs/nixos/modules/services/x11/display-managers/default.nix>
  #<nixpkgs/nixos/modules/services/x11/display-managers/gdm.nix>
  #<nixpkgs/nixos/modules/services/x11/display-managers/kdm.nix>
  #<nixpkgs/nixos/modules/services/x11/display-managers/lightdm.nix>
  #<nixpkgs/nixos/modules/services/x11/display-managers/slim.nix>
  #<nixpkgs/nixos/modules/services/x11/hardware/multitouch.nix>
  #<nixpkgs/nixos/modules/services/x11/hardware/synaptics.nix>
  #<nixpkgs/nixos/modules/services/x11/hardware/wacom.nix>
  #<nixpkgs/nixos/modules/services/x11/redshift.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/awesome.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/bspwm.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/default.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/fluxbox.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/icewm.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/metacity.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/none.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/twm.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/wmii.nix>
  #<nixpkgs/nixos/modules/services/x11/window-managers/xmonad.nix>
  #<nixpkgs/nixos/modules/services/x11/xfs.nix>
  #<nixpkgs/nixos/modules/services/x11/xserver.nix>
  #<nixpkgs/nixos/modules/system/boot/emergency-mode.nix>
  #<nixpkgs/nixos/modules/system/boot/kexec.nix>
  #<nixpkgs/nixos/modules/system/boot/loader/efi.nix>
  #<nixpkgs/nixos/modules/system/boot/loader/generations-dir/generations-dir.nix>
  #<nixpkgs/nixos/modules/system/boot/loader/grub/ipxe.nix>
  #<nixpkgs/nixos/modules/system/boot/loader/grub/memtest.nix>
  #<nixpkgs/nixos/modules/system/boot/loader/gummiboot/gummiboot.nix>
  #<nixpkgs/nixos/modules/system/boot/loader/init-script/init-script.nix>
  #<nixpkgs/nixos/modules/system/boot/loader/raspberrypi/raspberrypi.nix>
  #<nixpkgs/nixos/modules/system/boot/luksroot.nix>
  #<nixpkgs/nixos/modules/tasks/bcache.nix>
  #<nixpkgs/nixos/modules/tasks/encrypted-devices.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/btrfs.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/cifs.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/f2fs.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/jfs.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/nfs.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/reiserfs.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/unionfs-fuse.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/vfat.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/xfs.nix>
  #<nixpkgs/nixos/modules/tasks/filesystems/zfs.nix>
  #<nixpkgs/nixos/modules/tasks/lvm.nix>
  #<nixpkgs/nixos/modules/tasks/network-interfaces-scripted.nix>
  #<nixpkgs/nixos/modules/tasks/network-interfaces-systemd.nix>
  #<nixpkgs/nixos/modules/tasks/swraid.nix>
  #<nixpkgs/nixos/modules/tasks/trackpoint.nix>
  #<nixpkgs/nixos/modules/testing/service-runner.nix>
  #<nixpkgs/nixos/modules/virtualisation/amazon-options.nix>
  #<nixpkgs/nixos/modules/virtualisation/container-config.nix>
  #<nixpkgs/nixos/modules/virtualisation/libvirtd.nix>
  #<nixpkgs/nixos/modules/virtualisation/lxc.nix>
  #<nixpkgs/nixos/modules/virtualisation/openvswitch.nix>
  #<nixpkgs/nixos/modules/virtualisation/parallels-guest.nix>
  #<nixpkgs/nixos/modules/virtualisation/xen-dom0.nix>
]
