# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, attoparsec, either, exceptions, hspec, hspecWai
, httpTypes, network, networkUri, parsec, QuickCheck, safe, servant
, split, stringConversions, systemFilepath, temporary, text
, transformers, wai, waiAppStatic, waiExtra, warp
}:

cabal.mkDerivation (self: {
  pname = "servant-server";
  version = "0.2.4";
  sha256 = "11bds7zhkvqg9w27kb0dd792qvz8gjgkmkpbnijvwwzah5gmipi0";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson attoparsec either httpTypes networkUri safe servant split
    stringConversions systemFilepath text transformers wai waiAppStatic
    warp
  ];
  testDepends = [
    aeson either exceptions hspec hspecWai httpTypes network parsec
    QuickCheck servant stringConversions temporary text transformers
    wai waiExtra warp
  ];
  meta = {
    homepage = "http://haskell-servant.github.io/";
    description = "A family of combinators for defining webservices APIs and serving them";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
