# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, fetchzip, json, mtl, parsec, QuickCheck, regexTdfa
, transformers
}:

cabal.mkDerivation (self: {
  pname = "ShellCheck";
  version = "0.3.8";
  src = fetchzip {
    url = "http://hackage.haskell.org/package/ShellCheck-0.3.8/ShellCheck-0.3.8.tar.gz";
    sha256 = "1yya9gwiwzxwwjwx9rcriyllr9bskdqnv007p7wrkadvn4mj00vw";
  };
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    json mtl parsec QuickCheck regexTdfa transformers
  ];
  testDepends = [
    json mtl parsec QuickCheck regexTdfa transformers
  ];
  meta = {
    homepage = "http://www.shellcheck.net/";
    description = "Shell script analysis tool";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
