# Generated by jenkins4nix, https://github.com/zalora/jenkins4nix
# Command: jenkins4nix antisamy-markup-formatter console-column-plugin console-tail copyartifact credentials credentials-binding dashboard-view environment-dashboard external-monitor-job extra-columns ghprb git git-parameter github github-oauth google-login google-oauth-plugin jenkinswalldisplay jquery log-command mailer mapdb-api matrix-auth matrix-project nested-view oauth-credentials plain-credentials promoted-builds rebuild s3 script-security show-build-parameters simple-theme-plugin ssh-agent ssh-credentials ssh-slaves timestamper token-macro workflow-step-api slack parameterized-trigger
{
  "antisamy-markup-formatter" = {
    version = "1.3";
    sha1 = "b94e906e1f13b1333063cf620ae670bad3542240";
    depends = [  ];
  };
  "aws-java-sdk" = {
    version = "1.10.26";
    sha1 = "555e7a17e7662e5421c7b32e921cfd88ab95e5c3";
    depends = [  ];
  };
  "conditional-buildstep" = {
    version = "1.3.3";
    sha1 = "3acd06f560dadb9c9e75b10b7e1b2450ed99070d";
    depends = [ "token-macro" "run-condition" ];
  };
  "config-file-provider" = {
    version = "2.10.0";
    sha1 = "6f8ffc06a7e0d202ecda816ded74f81ad0a761bf";
    depends = [ "token-macro" "credentials" ];
  };
  "console-column-plugin" = {
    version = "1.5";
    sha1 = "9ad77fe5c4cd3301435e30cb4a5dc6791770c996";
    depends = [  ];
  };
  "console-tail" = {
    version = "1.1";
    sha1 = "dd875be276508de3c3284c52b5ab1416df97c186";
    depends = [  ];
  };
  "copyartifact" = {
    version = "1.37";
    sha1 = "594ab621e1cc21fa8fe3e8b1398a8e13808bca41";
    depends = [ "matrix-project" ];
  };
  "credentials" = {
    version = "1.24";
    sha1 = "9400dcaa054f2a332628073f5333842280be4fe8";
    depends = [  ];
  };
  "credentials-binding" = {
    version = "1.6";
    sha1 = "6e5db4be8240725612d0072a81f4819e40436ad9";
    depends = [ "credentials" "plain-credentials" ];
  };
  "dashboard-view" = {
    version = "2.9.6";
    sha1 = "78ab362d84b35bd48d164a59b8629a16b05433d8";
    depends = [  ];
  };
  "environment-dashboard" = {
    version = "1.1.4";
    sha1 = "8efd6dbb8c924776ac841badf880501becdc3ca3";
    depends = [ "jquery" ];
  };
  "external-monitor-job" = {
    version = "1.4";
    sha1 = "6969401bf7f766e38f1a6a2754201bd32ecfed01";
    depends = [  ];
  };
  "extra-columns" = {
    version = "1.16";
    sha1 = "54d4156c8ed7c476d4e1d30d97d23af4351ad0b0";
    depends = [  ];
  };
  "ghprb" = {
    version = "1.29.6";
    sha1 = "481c5355341416178209e42791dd25eb7c2b8a4f";
    depends = [ "matrix-project" "github-api" "git" "ssh-agent" "token-macro" "credentials" "plain-credentials" ];
  };
  "git" = {
    version = "2.4.0";
    sha1 = "5f6fcb3b43f25aef661c78585f2e9796f18b0a4a";
    depends = [ "git-client" "credentials" "ssh-credentials" "scm-api" "matrix-project" "mailer" "token-macro" "promoted-builds" ];
  };
  "git-client" = {
    version = "1.19.0";
    sha1 = "aea765523f4bf602adf3ee24fc8cf4124869f2e7";
    depends = [ "ssh-credentials" ];
  };
  "git-parameter" = {
    version = "0.4.0";
    sha1 = "b6f7bbfa5652ce0980f5d6dd0346a24e7de33598";
    depends = [ "credentials" "git" ];
  };
  "github" = {
    version = "1.14.0";
    sha1 = "8472f780bb60b97fe80658863d046a5e181eb144";
    depends = [ "github-api" "git" "credentials" "plain-credentials" ];
  };
  "github-api" = {
    version = "1.71";
    sha1 = "27321ac5dcbff5db99e97464f90f064517ef0516";
    depends = [  ];
  };
  "github-oauth" = {
    version = "0.22.2";
    sha1 = "a8a08062782404c6d0608722827decbcf28b4bfa";
    depends = [ "mailer" "github-api" "git" ];
  };
  "google-login" = {
    version = "1.2.1";
    sha1 = "1582db184cc3fc4a79b3f2624c8ec33872a47897";
    depends = [ "mailer" ];
  };
  "google-oauth-plugin" = {
    version = "0.4";
    sha1 = "e9afd46f206d22af97fe92818e461a894fa6cb09";
    depends = [ "oauth-credentials" ];
  };
  "jenkinswalldisplay" = {
    version = "0.6.30";
    sha1 = "bf5a7e4c00beb7371335517dcb91a3f71e6ffd27";
    depends = [ "nested-view" ];
  };
  "jquery" = {
    version = "1.11.2-0";
    sha1 = "78e9df74a02ad634c92c0e97279a9f4225c163aa";
    depends = [  ];
  };
  "junit" = {
    version = "1.10";
    sha1 = "3a22739b318ea026821741fdfad0e824f102c3b6";
    depends = [  ];
  };
  "log-command" = {
    version = "1.0.1";
    sha1 = "e3ade31612cc5bb24cd29e2578570074e9f1f203";
    depends = [  ];
  };
  "mailer" = {
    version = "1.16";
    sha1 = "3ffe05908197e4b80ce7ecb8c48471374da04c7b";
    depends = [  ];
  };
  "mapdb-api" = {
    version = "1.0.6.0";
    sha1 = "fe1bea979b187ed051d56e6042370f8c2359c74a";
    depends = [  ];
  };
  "matrix-auth" = {
    version = "1.2";
    sha1 = "91a7ebbee0c81b6fa5a954b182f11e7e4ba4a5d1";
    depends = [  ];
  };
  "matrix-project" = {
    version = "1.6";
    sha1 = "0b3cb0dff3a5dacdc75ae06ddbd85e13db8d91a2";
    depends = [ "junit" "script-security" ];
  };
  "nested-view" = {
    version = "1.14";
    sha1 = "6d3e852353e2ab7e45e32fe2a86ea5c3acec9b1b";
    depends = [  ];
  };
  "oauth-credentials" = {
    version = "0.3";
    sha1 = "4c355b5b36445ef15754c3e9ea1e885c9acad7ee";
    depends = [  ];
  };
  "parameterized-trigger" = {
    version = "2.29";
    sha1 = "fc8e1ce328ff2e2acdf98f8e73f7df2ad7aea593";
    depends = [ "subversion" "matrix-project" "promoted-builds" "conditional-buildstep" ];
  };
  "plain-credentials" = {
    version = "1.1";
    sha1 = "f459e09981859df206a4d9ee40d8bc3707c528ae";
    depends = [ "credentials" ];
  };
  "promoted-builds" = {
    version = "2.24";
    sha1 = "dcda9552e8d02bc8a1e263007cfb5c24e067f24c";
    depends = [ "token-macro" ];
  };
  "rebuild" = {
    version = "1.25";
    sha1 = "a62bbf56acc6bb851f60be8be0937334dd3fbc35";
    depends = [  ];
  };
  "run-condition" = {
    version = "1.0";
    sha1 = "0764ca10ef31e61300a6025778fa05d629bcee96";
    depends = [ "token-macro" ];
  };
  "s3" = {
    version = "0.8";
    sha1 = "0e4fcfa1a71b77ccf1001ac001cc1a0218e54c82";
    depends = [ "aws-java-sdk" "copyartifact" ];
  };
  "scm-api" = {
    version = "1.0";
    sha1 = "77e69ef2ebc915cd1d497860575f48a4412be76e";
    depends = [  ];
  };
  "script-security" = {
    version = "1.15";
    sha1 = "1ff014a4aa278db11db387aee2981297d89407d8";
    depends = [  ];
  };
  "show-build-parameters" = {
    version = "1.0";
    sha1 = "69ee5b0307cc907ce80c182cc80035c88311b9c0";
    depends = [  ];
  };
  "simple-theme-plugin" = {
    version = "0.3";
    sha1 = "ffec39d93f62916fe6aadbab75544d443c4efe5e";
    depends = [  ];
  };
  "slack" = {
    version = "1.8.1";
    sha1 = "92f2599baf9397d75e0edaeecd52e2d89e19cb52";
    depends = [  ];
  };
  "ssh-agent" = {
    version = "1.9";
    sha1 = "ec57bfe38b0fd7d88ca86d83083ba4dfba398d00";
    depends = [ "credentials" "ssh-credentials" ];
  };
  "ssh-credentials" = {
    version = "1.11";
    sha1 = "d47e6a2899ee75e48336f6d2637da4e9ba0e3d21";
    depends = [ "credentials" ];
  };
  "ssh-slaves" = {
    version = "1.10";
    sha1 = "18b00399db95b1e80982c94fe45cf5d4edee009b";
    depends = [ "credentials" "ssh-credentials" ];
  };
  "subversion" = {
    version = "2.5.4";
    sha1 = "fff0ffffd34b3ba22df8ca8ad2d46e79e91dbfcc";
    depends = [ "mapdb-api" "credentials" "ssh-credentials" "scm-api" ];
  };
  "timestamper" = {
    version = "1.7.2";
    sha1 = "cd0c0cc294235688f2e6abc510119e985fb903b0";
    depends = [  ];
  };
  "token-macro" = {
    version = "1.12";
    sha1 = "99f34b6725dab1505d8fb7ceca1150afd0f976a4";
    depends = [ "config-file-provider" ];
  };
  "workflow-step-api" = {
    version = "1.11";
    sha1 = "7d2656b1fc95d648078cb51aeb07f21a9ea42eae";
    depends = [  ];
  };
}
