#!@bash@/bin/bash

set -ef
set -o pipefail

export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt
export OPENSSL_X509_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

export PATH=@wtfenv@/bin:$PATH
export WTFDB=${WTFDB:-@wtfdb@}

test -f "$WTFDB"

if [ -t 1 ]; then
  WTF_ON_TERMINAL=1
else
  WTF_ON_TERMINAL=0
fi
export WTF_ON_TERMINAL

wait=0
checks=()
tags=()
nottags=( "slow" )
alwayschecks=()

wtfdb() {
  jq "$@" < "$WTFDB"
}

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      echo 'wtf [-w] [-t <tag>]... [-n <tag>]... [<check>...]'
      echo
      echo 'Available checks (name [tags]):'
      wtfdb -M -r 'to_entries[] | "\(.key) \(.value.tags)"'
      exit 0
    ;;
    -t|--tag)
      tags+=("$2")
      shift
    ;;
    -n|--nottag)
      nottags+=("$2")
      shift
    ;;
    -w|--wait)
      wait=1 # poll until the check starts returning zero
    ;;
    *)
      alwayschecks+=("$1")
    ;;
  esac
  shift
done

checks=$(
  wtfdb \
      -r -s \
      --arg ytags "${tags[*]}" \
      --arg ntags "${nottags[*]}" \
      --arg names "${alwayschecks[*]}" \
      '
        ($ytags / " ") as $ytags |
        ($ntags / " " - $ytags) as $ntags |
        ($names / " ") as $names |

        def in(xs):
          . as $i | xs | map(. == $i) | any;

        def enabled_by_name(x):
          x.name | in($names);

        def enabled_by_ytags(x):
          (($ytags | length) == 0 and ($names | length) == 0) or
          (x.tags | map(in($ytags)) | any);

        def disabled_by_ntags(x):
          x.tags | map(in($ntags)) | any;

        def enabled_by_tags(x):
          enabled_by_ytags(x) and (disabled_by_ntags(x) | not);

        def enabled(x):
          enabled_by_name(x) or
          enabled_by_tags(x);

        add | to_entries[] | .value | select(enabled(.)) |
          @sh "wtf_wrapper=\(."wtf-wrapper") name=\(.name)"
      '
)

run() {
  echo "$checks" | xargs -d '\n' -P 0 -I {} bash -o pipefail -e -c '
    {}

    logfile=/dev/null
    if [ -d "$WTFLOGS" ]; then
      logfile=$WTFLOGS/$name.log
    fi

    prefix() {
      date "+%Y-%m-%d %H:%M:%S $name START" >> "$logfile"
      while read line; do
        echo "$name: $line"
        echo "$line" >> "$logfile"
      done
      date "+%Y-%m-%d %H:%M:%S $name DONE" >> "$logfile"
    }

    "$wtf_wrapper" 2>&1 | prefix
  '
}

if test -z "$checks"; then
  echo 'No checks selected!' >&2
else
  while ! run && [ $wait -eq 1 ]; do
    sleep 1
  done
fi
