# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, hspec, parsec, QuickCheck, stringConversions, text }:

cabal.mkDerivation (self: {
  pname = "servant";
  version = "0.2.2";
  sha256 = "1pblmnarq1939d2krwbmd9ssm68ar9ip54dl28zjv2j51vhhhzhc";
  buildDepends = [ parsec stringConversions text ];
  testDepends = [ hspec parsec QuickCheck stringConversions text ];
  meta = {
    homepage = "http://haskell-servant.github.io/";
    description = "A family of combinators for defining webservices APIs";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
