# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, fetchzip, mtl }:

cabal.mkDerivation (self: {
  pname = "mtl-compat";
  version = "0.2.1.3";
  src = fetchzip {
    url = "http://hackage.haskell.org/package/mtl-compat-0.2.1.3/mtl-compat-0.2.1.3.tar.gz";
    sha256 = "0a9b8mmjmsip8dc23574r2mpa7nypgf633zwlsb7dwld927iiz0m";
  };
  buildDepends = [ mtl ];
  noHaddock = true;
  meta = {
    homepage = "https://github.com/RyanGlScott/mtl-compat";
    description = "Backported Control.Monad.Except module from mtl";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
