#! /bin/sh
#
# usage: retry COMMAND [ARGS...]
#
# Retry to run a command successfully with configurable delays between runs.
#
# Notice that the command won't receive any data via standard input.
#
set -euf

export PATH=@coreutils@/bin"${PATH+:$PATH}"

# By default try to run command 10 times with a delay of 3s between retries.
retry_count=${RETRY_COUNT:-10}
retry_delay=${RETRY_DELAY:-3}

# retry_delay_seq specifies the delays between unsuccessful attempts to run the
# command as space separated list of sleep arguments.  See also sleep(1).
#
# Notice how this sequence is one less than the desired number of retries
# because we don't need to wait after the last failed attempt.
#
# You can override this variable to e.g. implement a non-linear retry schema.
retry_delay_seq=${RETRY_DELAY_SEQ:-$(
  for i in $(seq 2 $retry_count); do
    echo $retry_delay
  done
)}

# main COMMAND [ARGS...]
main() {
  try_exec "$@"
  for delay in $retry_delay_seq; do
    echo "$0: \`$@\` exit code $exit_code; retrying after sleep $delay..." >&2
    sleep $delay
    try_exec "$@"
  done
  echo "$0: \`$@\` exit code $exit_code; giving up." >&2
  exit $exit_code
}

# try_exec COMMAND [ARGS...]
# If command exits with a zero exit code, then try_exec will exit the current
# process (mimicking the behavior of exec).  Otherwise set the exit_code
# variable for further inspection (or retry in our case).
try_exec() {
  if env "$@" </dev/null; then
    exit
  else
    exit_code=$?
  fi
}

main "$@"
